name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 912656312251.dkr.ecr.us-east-1.amazonaws.com/helloaws
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 912656312251.dkr.ecr.us-east-1.amazonaws.com/helloaws:latest
